# Generated by Django 5.0.7 on 2025-05-26 23:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profile_page', '0001_initial'),
        ('search', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='institutionprofile',
            name='professionals',
            field=models.ManyToManyField(blank=True, related_name='institutions', to='profile_page.professionalprofile'),
        ),
        migrations.AlterField(
            model_name='professionalprofile',
            name='specializations',
            field=models.ManyToManyField(blank=True, related_name='professionals', to='search.category'),
        ),
    ]
